module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#8ef4e9",
        "tertiary-container": "#f9d593",
        background: "#fff8f6",
        "on-tertiary-container": "#614914",
        surface: "#fff8f6",
        "surface-container-high": "#fae3dd",
        "surface-container-low": "#fff1ed",
        tertiary: "#755b25",
        "on-primary": "#fff7f5",
        "on-surface": "#3e2f2b",
        "surface-container-highest": "#f6ddd7",
        "on-secondary-fixed": "#004843",
        "surface-variant": "#f6ddd7",
        "on-secondary-container": "#005c56",
        "inverse-on-surface": "#a79a96",
        "tertiary-fixed-dim": "#eac787",
        "surface-container": "#ffe9e4",
        "primary-fixed-dim": "#ec7b58",
        "surface-bright": "#fff8f6",
        "on-primary-fixed-variant": "#621800",
        "on-error": "#fff7f6",
        "on-secondary-fixed-variant": "#006760",
        secondary: "#006b64",
        "secondary-fixed-dim": "#7fe6db",
        "primary-fixed": "#fd8863",
        "on-surface-variant": "#6d5b56",
        "outline-variant": "#c3ada7",
        "secondary-dim": "#005e57",
        outline: "#8a7671",
        error: "#a83836",
        "secondary-container": "#8ef4e9",
        "surface-tint": "#a04223",
        "on-secondary": "#e2fffa",
        "tertiary-fixed": "#f9d593",
        "on-tertiary-fixed": "#4c3602",
        "primary-container": "#fd8863",
        "error-container": "#fa746f",
        "on-primary-fixed": "#1e0300",
        "on-tertiary": "#fff8f1",
        primary: "#a04223",
        "inverse-primary": "#fd8863",
        "surface-container-lowest": "#ffffff",
        "on-error-container": "#6e0a12",
        "inverse-surface": "#130d0b",
        "on-background": "#3e2f2b",
        "tertiary-dim": "#684f1a",
        "on-tertiary-fixed-variant": "#6b521d",
        "primary-dim": "#903618",
        "on-primary-container": "#531300",
        "error-dim": "#67040d",
        "surface-dim": "#edd5ce",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans"],
        body: ["Be Vietnam Pro"],
        label: ["Plus Jakarta Sans"],
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
